name: kite
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  easy_image_viewer: ^1.5.1
  universal_image: ^1.0.9
  flutter_html: ^3.0.0
  
  go_router: ^15.0.0
  
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  intl: ^0.19.0
  http: ^1.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_svg: ^2.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  mocktail: ^1.0.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/kite_dark.svg
flutter_native_splash:
         color: "#FFFFFF"
         image: assets/kite_dark.png
         ios: true
         android: true
